# Generated by Django 3.1.7 on 2021-03-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retrieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(choices=[('dataextention', 'dataextention'), ('SQLquery', 'SQLquery')], default='dataextention', max_length=20)),
                ('stack', models.CharField(choices=[('s1', 's1'), ('s4', 's4'), ('s6', 's6'), ('s7', 's7'), ('s8', 's8'), ('s10', 's10'), ('s11', 's11')], default='s10', max_length=5)),
                ('word', models.CharField(max_length=1000)),
            ],
        ),
    ]
